### DISCUSSION TITLE
Unexplained slowdown near singularity

### DISCUSSION THREAD

**Discussion by bjwindham** [Yaskawa-Global/motoros2#211] [Troubleshooting]
On occasion when using Moveit and OMPL to generate paths for my GP88, a valid path will be found, and I'll send the plan to the robot. All that will happen is that the visualization in RVIZ will move **_very_** slowly while my actual robot won't move at all and I just get stuck with a message in my terminal stating "Execute request accepted". I think the culprit is that the trajectory created by OMPL is over the size limit.

If I turn up the velocity scaling factor, thus increasing available speed, it becomes less and less of an issue. However, I have a lot of expensive and fragile equipment attached to my end effector, so reducing speed to comfortable level is ideal.

As I've turned up the velocity I've noticed that I'm having an issue where when my GP88 is near-singular, I get a noticeable slowdown. I'm using OMPL so I assume that all planning takes place in joint space thus, there should be no issue with singularities. The only thing I can think of is that since I do have constraints on my end effector (they're pretty liberal), maybe that could be part of it? Or is there some logic on the Yaskawa side that limits joint velocities when near singular?

I've been chasing the issue for a couple days now. Has anyone seen a similar issue or have insight as to why this may be happening? I also checked to see if I had any limitations from the FSU and there is nothing listed on my teach pendant.

Below is a google drive link so you can see the speed being limited when the manipulator is near-singular. 

I appreciate any insight that anyone can provide.

https://photos.app.goo.gl/yjnhg3V4AVZzf9jh8

**Comment by gavanderhoorn** [comment]
Could you please attach an example of a trajectory which has the slowdown you observe?

An example of a trajectory which results in the "stuck terminal" would also be nice, as we could check a couple of things.

---

Edit: oh and please also attach a copy of a debug listener log of a session which has the slowdown.

**Reply by bjwindham** [reply]
I will try to get you this information. I'm still **_very_** new to ROS2 and C++ and I don't know exactly how to pull out the trajectory information from the plan returned from moveit::planning_interface::MoveGroupInterface::Plan. I will try to figure it out today.

**Reply by gavanderhoorn** [reply]
The `Plan` `struct` contains the trajectory in one of the fields ([docs](https://moveit.picknik.ai/main/api/html/structmoveit_1_1planning__interface_1_1MoveGroupInterface_1_1Plan.html)). That'd be a [RobotTrajectory](https://github.com/ros-planning/moveit_msgs/blob/0e203aaffd1f754ab3b31110eff0eaf26e1c3599/msg/RobotTrajectory.msg), which has the [JointTrajectory](https://github.com/ros-planning/moveit_msgs/blob/0e203aaffd1f754ab3b31110eff0eaf26e1c3599/msg/RobotTrajectory.msg#L1C33-L1C49) in one of its members.

**Comment by bjwindham** [comment]
So, I'd want to do something along the lines of saving plan.trajectory.joint_trajectory as something like a .txt file so it can be shared? I apologize for the noob questions.

**Comment by bjwindham** [comment]
gavanderhoorn, I have a .txt file with the trajectories in it. Note that there are 3 trajectories, and that if "failed" on the last one. By "failed", I mean, came up with a valid plan moved in RVIZ (very slowly) and my actual hardware made no movement. It seems like when the time to complete a trajectory is greater than 12.7 seconds, it fails. Attached is the .txt of trajectories.
[GP88_trajectories.txt](https://github.com/Yaskawa-Global/motoros2/files/14168660/GP88_trajectories.txt)

**Reply by gavanderhoorn** [reply]
Could you explain how you output that file?

I ask because the last one contains something like this:

<details>
<summary>Click to expand</summary>

```yaml
model_id: world
trajectory:
- joint_trajectory:
    header: [..]
    joint_names: [..]
    points:
    ... more points ...
    - positions:
      - -0.02920892075048393
      - -0.6390092815841684
      - -0.8376062897863009
      - -0.6235613123597488
      - 0.12063757194158509
      - 0.611555338433316
      velocities:
      - 0.003729418827372026
      - -0.03963063787357617
      - -0.037572505288790775
      - -0.3211405753442613
      - 0.011466726821354384
      - 0.3235999761980261
      accelerations:
      - -0.00033351499782037383
      - 0.004479532992792473
      - 0.00377676099198349
      - -1.9598819499454597e-07
      - -0.034507073728178655
      - -9.737011687427629e-05
      effort: []
      time_from_start:
        sec: 12
        nanosec: 700000000
    - '...'
```

</details>

That last `'...'` is a string, and it's not from me eliding more elements. It's also at the same indentation level as the other elements in `points`, which makes me wonder whether something got truncated.

Ignoring the `'...'`, this trajectory currently contains 128 `JointTrajectoryPoint`s, so theoretically, it *should* execute. But if there were more points, it could be it indeed exceeds the 200 point maximum we currently have set.

Could you please also still attach the [debug logger output](https://github.com/Yaskawa-Global/motoros2/blob/10d8f00317c5d4ef7960627962337bf72e2ba817/doc/troubleshooting.md#debug-log-client) for a session which results in no-motion? That should give us some more insight into what is happening on the controller side.
