### DISCUSSION TITLE
The robot doesn’t move

### DISCUSSION THREAD

**Discussion by yuutayuuta50** [Yaskawa-Global/motoros2#318] [Q&A] [answered]
Here are two things I am currently able to do:

1. Start the micro-ROS agent and obtain the joint angles of the GP4 via ros2 topic echo /joint_states.

2. Operate the GP4 in simulation using the configuration files created with the Setup Assistant.

I don't know how to connect it with the actual robot, so if you have any reference materials, configuration files, or source code, I would appreciate it if you could share them.

**Comment by ted-miller** [comment]
Hi @yuutayuuta50 
It's good to hear that the robot is successfully communicating/publishing. Unfortunately, we are not able to provide support for MoveIt2 usage in this repository. 

I suggest reviewing this guide, which was created by Yaskawa Europe.
https://github.com/YaskawaEurope/ros2-starter-for-yaskawa-robots/tree/main

It steps you through the process of configuring everything and includes sample source code for basic motion.

**Reply by yuutayuuta50** [reply]
Thank you for the guidance! I’ll go through the Yaskawa Europe guide and try to configure everything accordingly.

**Comment by yuutayuuta50** [comment]
I was able to display the actual robot's joint angles in RViz using the following: https://github.com/YaskawaEurope/ros2-starter-for-yaskawa-robots/tree/main

However, the robot does not move. Is there a way to operate the robot using motoros2 alone to test whether the installation was successful? Or can we consider the installation successful if the joint states are displayed?

**Reply by ted-miller** [reply]
Since you're seeing the joints, you should be in good shape.

But if you want to verify that the robot is "motion ready", then the easiest way is to use the command line interface and manually invoke the `start_traj_mode` service. If it is successful, then servo power will be enabled and the `robot_status` topic will indicate `motion_possible = TRUE`.

First, build the `motoros2_client_interface_dependencies` [workspace](https://github.com/Yaskawa-Global/motoros2_client_interface_dependencies). Then source this environment with `source install/local_setup.bash`

`ros2 service call /start_traj_mode motoros2_interfaces/srv/StartTrajMode`
then
`ros2 topic echo /robot_status`

**Reply by yuutayuuta50** [reply]
I executed the following command, and the robot is now in the servo-on state:

ros2 service call /yaskawa/start_traj_mode motoros2_interfaces/srv/StartTrajMode

After running ros2 topic echo /yaskawa/robot_status, the following result was displayed:

```yaml
header:
  stamp:
    sec: 1728613108
    nanosec: 204026093
  frame_id: ''
mode:
  val: 2
e_stopped:
  val: 0
drives_powered:
  val: 1
motion_possible:
  val: 1
in_motion:
  val: 0
in_error:
  val: 0
error_codes: []
```

**Comment by yuutayuuta50** [comment]


**Reply by lkaising** [reply]
It's difficult to pinpoint the issue solely from the console output of the `xy_start.launch.py` file. From the logs, everything looks fine at first glance, but one thing stands out: the controller configuration. It seems like no controller has been set, as I don't see any reference to controllers being listed or loaded during the launch. This typically suggests that the controller setup in the MoveIt2 configuration is missing or incomplete.

To use MoveIt2 properly, you'll need to ensure that the `ros2_controllers.yaml` and `moveit_controllers.yaml` files under your `moveit_resources_moto_moveit_config` package are properly set up. The `follow_joint_trajectory` controller should be configured and active, as it's required for MoveIt2 to execute joint trajectory commands. You can refer to the [Motoros2 README](https://github.com/Yaskawa-Global/motoros2/blob/main/README.md) under the "Usage" section, which outlines how to configure the controller to use `follow_joint_trajectory`.

Without seeing your MoveIt configuration package, including the `ros2_controllers.yaml` and `moveit_controllers.yaml` files, and the full content of your launch file, it's hard to diagnose the problem more specifically. If you share these files, I'd be happy to take a closer look and provide more detailed feedback.

**Reply by yuutayuuta50** [reply]
I’m not confident about how to properly launch the controllers when using the actual robot. I would appreciate it if you could take a look at the key files, which I’ve attached. I’ll also include the controller section in this message.

I have confirmed that the robot works fine in the simulation, and when I run "ros2 control list_controllers", the controllers are listed. However, when using the actual hardware, no controllers appear.

[files.zip](https://github.com/user-attachments/files/17370572/files.zip)

【.py.launch】
```python
    moveit_config = (
        MoveItConfigsBuilder("moveit_resources_moto")
        .robot_description(file_path="config/moto.urdf.xacro")
        .robot_description_semantic(file_path="config/moto.srdf")
        .trajectory_execution(file_path="config/moveit_controllers.yaml")
        .to_moveit_configs()
    )
     planning_scene_monitor_parameters = {
        "publish_planning_scene": True,
        "publish_geometry_updates": True,
        "publish_state_updates": True,
        "publish_transforms_updates": True,
        "publish_robot_description": True,
        "publish_robot_description_semantic": True,
    }
    # Start the actual move_group node/action server
    # robot
    run_move_group_nodeX = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[
            moveit_config.to_dict(),
            planning_scene_monitor_parameters,
        ],
    )
    # ↓don't use
    # Start the actual move_group node/action server
    # simulation
    run_move_group_node = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[
            moveit_config.to_dict(),
            planning_scene_monitor_parameters,
        ],
        remappings=[('joint_states', '/moto_controller/joint_states'),
                    ('joint_states', '/yaskawa/joint_states')]
    )
    return LaunchDescription(
        [
            run_move_group_nodeX,
            joint_state_publisherX,
            robot_state_publisherX,
            rviz_node,
            #run_move_group_node, ### _1 #don't use
            #ros2_control_node, #don't use
        ]
    )
```

【moveit_controllers.yaml】
```python
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true
  
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - /yaskawa

  /yaskawa:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
```

【ros2_controllers.yaml】

```yaml
#This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    yaskawa:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
yaskawa:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
```

**Reply by lkaising** [reply]
Looking over your `motoros2_config.yaml`, was there any particular reason you set the `node_namespace` to `yaskawa`? In my current setup (I have the GP4 arm working with MoveIt), I left the `node_namespace` at its default value.

In your `ros2_controllers.yaml`, instead of using `yaskawa`, I used `follow_joint_trajectory`, which looks like this:

```yaml
# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    follow_joint_trajectory:
      type: joint_trajectory_controller/JointTrajectoryController

follow_joint_trajectory:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
```

This change would require you to update your MoveIt controller from `yaskawa` to `follow_joint_trajectory`. I also noticed that in your `moveit_controllers.yaml` file, you used `/yaskawa` instead of `yaskawa`. Was there a specific reason for this? It might be causing a mismatch between your ROS controllers and MoveIt controllers.

Additionally, in my implementation of `moveit_controllers.yaml`, I found that setting `action_ns` to an empty string `""` rather than `follow_joint_trajectory` allowed the actual robot to move. The trade-off is that setting `action_ns` to `""` causes the RViz simulated planners to fail, but the robot does move. I accepted this compromise because I intended to interact with the robot using MoveIt directly (e.g., MoveGroup interface or MoveIt Task Constructor) rather than through RViz. Here's my implementation of `moveit_controllers.yaml`:

```yaml
# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 10.0
  allowed_goal_duration_margin: 10.0
  allowed_start_tolerance: 0.1
  trajectory_duration_monitoring: false

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - follow_joint_trajectory

  follow_joint_trajectory:
    type: FollowJointTrajectory
    action_ns: ""
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
```

Also, I looked over your launch file `xy_start.launch.py`, and it seems you're handling the loading of controllers differently than I did. Here's how I did it, and I haven't had any issues:

```python
# Load controllers
load_controllers = []
for controller in [
    "follow_joint_trajectory",
]:
    load_controllers += [
        ExecuteProcess(
            cmd=["ros2 run controller_manager spawner {}".format(controller)],
            shell=True,
            output="screen",
        )
    ]

# Other nodes

return LaunchDescription(
    [
        rviz_node,
        static_tf,
        robot_state_publisher,
        run_move_group_node,
        ros2_control_node,
        run_core_application_node,
    ]
    + load_controllers
)
```

By explicitly spawning the `follow_joint_trajectory` controller in the launch file, you ensure that it's properly loaded and active when you start your application. This might help resolve the issue of the robot not moving.

Suggestions:

1. Consider leaving `node_namespace` at its default value in `motoros2_config.yaml`.
2. Change `yaskawa` to `follow_joint_trajectory` in both `ros2_controllers.yaml` and `moveit_controllers.yaml` to prevent potential mismatches.
3. Set `action_ns` to an empty string `""` in `moveit_controllers.yaml` if you intend to interact with the robot directly rather than through RViz.
4. Modify your launch file to explicitly load the controllers, ensuring they are active when your application starts.

I hope these suggestions help you get your robot moving!

**Reply by yuutayuuta50** [reply]
Thank you very much for reviewing my files and providing such detailed explanations. I really appreciate your insights and will try your suggestions right away.

I have one additional question: Could you provide guidance on the proper way to launch the ros2_control_node? Currently, I’m using the following launch file along with a xacro file containing moto.ros2_control.xacro. While this setup works well for simulation, I’m unsure if it’s correct for the real robot.

【.launch.py】：
```python
#ros2_control using FakeSystem as hardware
ros2_controllers_path = os.path.join(
    get_package_share_directory("moveit_resources_moto_moveit_config"),
    "config",
    "ros2_controllers.yaml",
)
ros2_control_node = Node(
    package="controller_manager",
    executable="ros2_control_node",
    parameters=[moveit_config.robot_description, ros2_controllers_path],
    output="both",
)
```

【.urdf.xacro】：
```xml
<xacro:include filename="moto.ros2_control.xacro" />
<xacro:moto_ros2_control name="motoFakeSystem" initial_positions_file="$(arg initial_positions_file)"/>
```

**Reply by lkaising** [reply]
From what I see in your code snippet, it looks mostly correct, but there might be a small issue with how the `.ros2_control.xacro` file is being referenced. It’s a good idea to specify the full package name where your `.ros2_control.xacro` file is located to avoid any path issues. You can do this by prefixing the file name with something like:

```xml
<xacro:include filename="$(find YOUR_ROBOT_MOVEIT_CONFIG)/config/YOUR_ROBOT.ros2_control.xacro" />
```

Here’s a general template you can use as a guideline to ensure everything is linked properly:

```xml
<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="YOUR_ROBOT_NAME">
  <xacro:arg name="initial_positions_file" default="$(find YOUR_ROBOT_MOVEIT_CONFIG)/config/initial_positions.yaml" />

  <!-- Include necessary Xacro files -->
  <xacro:include filename="$(find YOUR_ROBOT_DESCRIPTION)/urdf/YOUR_ROBOT.urdf.xacro" />
  <xacro:include filename="$(find YOUR_ROBOT_MOVEIT_CONFIG)/config/YOUR_ROBOT.ros2_control.xacro" />

  <!-- Instantiate the ROS 2 control macro -->
  <xacro:YOUR_ROBOT_ROS2_CONTROL
    name="FakeSystem"
    initial_positions_file="$(arg initial_positions_file)" />
</robot>
```

Hope this helps!

_One small note: Consider using Markdown for code snippets in discussion posts, it improves formatting and readability, just in case you weren't aware._

**Reply by yuutayuuta50** [reply]
![Screenshot from 2024-10-16 16-10-17](https://github.com/user-attachments/assets/5f0dbfda-ec95-4804-b478-da318c2c7259)

After applying the corrections as you suggested, it seems that the controller is up and running, but the robot is not moving. The attached files are my final configuration settings. Would it be possible for you to share a complete set of files (especially ros_control.xacro, urdf.xacro, motoros2_config.yaml and launch.py) that allows the robot to move in RViz?

[files.zip](https://github.com/user-attachments/files/17391413/files.zip)

**Comment by yuutayuuta50** [comment]
I've tried various approaches, and it seems that setting action_ns to "" causes issues when launching the controller. When I set action_ns to follow_joint_trajectory, the robot does not move, but the process completes without any errors.

Is it possible to use the Plan and Execute buttons in RViz's motion planning to move the actual robot?

**Reply by gavanderhoorn** [reply]
Just to clarify: `ros2_control` is *not* used by MotoROS2, nor supported. There is no MoveIt configuration using `ros2_control` which can communicate with MotoROS2.

All the files the MoveIt Setup Assistant generated for use with `ros2_control` can be ignored (I would even go so far as to remove them).

What is needed is to configure MoveIt with a `FollowJointTrajectoryAction` client. That's the `moveit_simple_controller_manager/MoveItSimpleControllerManager` configuration @lkaising shows in the second codeblock in https://github.com/Yaskawa-Global/motoros2/discussions/318#discussioncomment-10950931 does.

**Comment by yuutayuuta50** [comment]
Thank you for your response.

I still cannot get the robot to move. Based on the URL below and your advice, I have set up the moveit_controllers.yaml and launched the MoveGroup node. However, instead of using RViz, I used hello_moveit.cpp, where the planning succeeds, but it stops at the message 'sending trajectory to follow_joint_trajectory' when executing "move_group_interface.asyncExecute(plan);"

https://github.com/YaskawaEurope/ros2-starter-for-yaskawa-robots/tree/main

If a controller is necessary, is there a way to create one without using ros2_control? I haven't been able to find any information on how to do this anywhere. Alternatively, if the current setup should be sufficient, could it be that there is an issue with my yrc10000? Incidentally, when I use ROS (not ROS2), my yrc1000 works and I can move the robot.


<details>
<summary>moveit_controllers.yaml</summary>

```
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true


moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - follow_joint_trajectory

  follow_joint_trajectory:
    type: FollowJointTrajectory
    action_ns: ""
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: ""
    default: true
```
</details>

<details>
<summary>launch.py</summary>

```python
def generate_launch_description():
    motoman_directory = "robo"
    ns = ""
    # URDF
    motoman_robot_description_config = xacro.process_file(
        os.path.join(
            get_package_share_directory(motoman_directory),
            "config",
            "motoman_gp4.urdf.xacro",
        ),
        # mappings={'prefix': '/yaskawa_a1/'},
    )
    motoman_robot_description = {
        "robot_description": motoman_robot_description_config.toxml()
    }
    moveit_config = (
        MoveItConfigsBuilder("motoman_gp4", package_name="robo")
        .robot_description(file_path="config/motoman_gp4.urdf.xacro")
        .robot_description_semantic(file_path="config/motoman_gp4.srdf")
        .trajectory_execution(file_path="config/moveit_controllers.yaml")
        .to_moveit_configs()
    )
    planning_scene_monitor_parameters = {
        "publish_planning_scene": True,
        "publish_geometry_updates": True,
        "publish_state_updates": True,
        "publish_transforms_updates": True,
        "publish_robot_description": True,
        "publish_robot_description_semantic": True,
    }
    #logger.info(moveit_config.to_dict())
    # Start the actual move_group node/action server
    # simulation
    run_move_group_nodeX = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        namespace=ns,
        parameters=[
            moveit_config.to_dict(),
            planning_scene_monitor_parameters,
            # {"use_sim_time": True},
        ],
        # remappings=[('/moto_controller/joint_states', '/yaskawa/joint_states')]
        #remappings=[('joint_states', '/follow_joint_trajectory/joint_states')]
    )
    # RViz
    rviz_base = os.path.join(
        get_package_share_directory(
            "robo"), "launch"
    )
    rviz_full_config = os.path.join(rviz_base, "moveit.rviz")
    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="log",
        arguments=["-d", rviz_full_config],
        parameters=[
            moveit_config.robot_description,
            moveit_config.robot_description_semantic,
            moveit_config.planning_pipelines,
            moveit_config.robot_description_kinematics,
            # {"use_sim_time": True},
        ],
    )
    # Publish TF
    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="both",
        namespace=ns,
        parameters=[moveit_config.robot_description],
        #remappings=[('joint_states', '/joint_state_broadcaster/joint_states')]
    )
    # ros2_control using FakeSystem as hardware
    ros2_controllers_path = os.path.join(
        get_package_share_directory("robo"),
        "config",
        "ros2_controllers.yaml",
    )
    ros2_control_node = Node(
        namespace=ns,
        package="controller_manager",
        executable="ros2_control_node",
        parameters=[moveit_config.robot_description, ros2_controllers_path],
        output="both",
    )
    joint_state_publisherX = Node(
        package='joint_state_publisher',
        executable='joint_state_publisher',
        name='joint_state_publisher',
        namespace=ns,
        parameters=[
            {
                "robot_description": motoman_robot_description,
                "rate": 43,
                "source_list": ['/joint_states'],
            }
        ],
    )
    robot_state_publisherX = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        output="both",
        namespace=ns,
        parameters=[moveit_config.robot_description]
    )
    moto_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        namespace=ns,
        arguments=[
            "follow_joint_trajectory",
            "--controller-manager",
            "/controller_manager",
        ],
    )
    return LaunchDescription(
        [
            # db_arg,
            # static_tf,
            # mongodb_server_node,
            run_move_group_nodeX,
            joint_state_publisherX,
            robot_state_publisherX,
            #robot_state_publisher,
            rviz_node,
            #run_move_group_node, ### _1
            #ros2_control_node,
            #joint_state_broadcaster_spawner,
            #moto_controller_spawner,
        ]
        # + load_controllers
    )
```
</details>

<details>
<summary>hello_moveit.cpp</summary>

```cpp
#include <memory>

#include "motoros2_interfaces/srv/start_traj_mode.hpp"
#include "std_srvs/srv/trigger.hpp"

#include <rclcpp/rclcpp.hpp>
#include <moveit/move_group_interface/move_group_interface.h>

#include <rclcpp/rclcpp.hpp>
#include <moveit/moveit_cpp/moveit_cpp.h>
#include <moveit/moveit_cpp/planning_component.h>

#include <chrono>
#include <thread>

int main(int argc, char *argv[])
{
  //-----------------------------------------------------
  rclcpp::init(argc, argv);

  //-------------------controller enable-----------------------------
  auto drive = rclcpp::Node::make_shared("enable_client");

  auto enable_client = drive->create_client<motoros2_interfaces::srv::StartTrajMode>("/start_traj_mode");

  // Create a request message to send
  auto request = std::make_shared<motoros2_interfaces::srv::StartTrajMode::Request>();

  // Send the request asynchronously
  auto future = enable_client->async_send_request(request);

  std::this_thread::sleep_for(std::chrono::seconds(5));

  //-----------------------------------------------------

  auto const node = std::make_shared<rclcpp::Node>(
      "hello_moveit", rclcpp::NodeOptions().automatically_declare_parameters_from_overrides(true));

  // Create a ROS logger
  auto const logger = rclcpp::get_logger("hello_moveit");

  // Create the MoveIt MoveGroup Interface
  using moveit::planning_interface::MoveGroupInterface;
  auto move_group_interface = MoveGroupInterface(node, "flange");

  // Set a target Pose
  auto const target_pose = []
  {
    geometry_msgs::msg::Pose msg;
    msg.orientation.x = 0.0;
    msg.orientation.y = 0.0;
    msg.orientation.z = 0.0;
    msg.orientation.w = 1.0;
    msg.position.x = 0.44;  // 0.44;
    msg.position.y = 0.0;  // 0.1;
    msg.position.z = 0.60; // 0.73;
    return msg;
  }();
  move_group_interface.setPoseTarget(target_pose);

  // Create a plan to that target pose
  auto const [success, plan] = [&move_group_interface]
  {
    moveit::planning_interface::MoveGroupInterface::Plan msg;
    auto const ok = static_cast<bool>(move_group_interface.plan(msg));
    return std::make_pair(ok, msg);
  }();

  std::this_thread::sleep_for(std::chrono::seconds(5));
  // Execute the plan
  if (success)
  {
    RCLCPP_INFO(logger, "Planning OK!");
    // move_group_interface.execute(plan);
    move_group_interface.asyncExecute(plan);
    std::this_thread::sleep_for(std::chrono::seconds(10));
    RCLCPP_INFO(logger, "end of waiting");
  }
  else
  {
    RCLCPP_ERROR(logger, "Planning failed!");
  }

  rclcpp::shutdown();
  return 0;
}
```
</details>
