### DISCUSSION TITLE
linear axis values are in millimeters instead of meters

### DISCUSSION THREAD

**Discussion by schornakj** [Yaskawa-Global/motoros2#354] [Troubleshooting] [answered]
I have a GP180 arm mounted on a linear rail which serves as a base axis, both connected to a DX200 controller. When I run MotoROS2 the joint state for the linear rail is reported in units of millimeters rather than in units of meters like I'd expect.

It looks like the [`GP_getPulseToMeter()`](https://github.com/Yaskawa-Global/motoros2/blob/8feb9c63e42a3704496cfdcacca711a0da6fcc89/lib/CmosParameterExtraction.h#L134-L143) function retrieves the conversion factor from axis pulses to meters for a specific control group from the controller's memory, and then that value is used when creating JointState messages [to convert to meters](https://github.com/Yaskawa-Global/motoros2/blob/8feb9c63e42a3704496cfdcacca711a0da6fcc89/src/CtrlGroup.c#L512-L538). Based on how the code is written I'd expect that all joint states published will either be in radians or meters.

I think that this conversion is something I can configure somewhere on the controller, but I haven't found what menu contains this setting yet. I also want to make sure I correctly understand how this data gets retrieved by MotoROS2.  Am I on the right track with all this so far?

**Comment by gavanderhoorn** [comment]
I've converted this to a discussion in the *Troubleshooting* category as MotoROS2 should already be reporting `JointState` values in metres (for linear axes). Always.

If it doesn't, something is wrong.

@schornakj: could you provide a couple of sample `JointState` messages from your DX200 published by MotoROS2?

---

Edit: and I also expect @ted-miller will ask for a `PANELBOX.LOG` copy and possibly a `CMOS.BIN` copy.

**Reply by ted-miller** [reply]
> @ted-miller will ask for a PANELBOX.LOG copy and possibly a CMOS.BIN copy.

Yes. I can validate the gearing ratios are configured properly for the track.

**Reply by schornakj** [reply]
Thank you, I'll get this info for you.

**Reply by schornakj** [reply]
@ted-miller Here are `PANELBOX.LOG` and `CMOS.BIN` from my robot:

[joe_robot_diagnostics.zip](https://github.com/user-attachments/files/18415604/joe_robot_diagnostics.zip)

@gavanderhoorn here is a sample joint state:

```
header:
  stamp:
    sec: 1736882630
    nanosec: 168289013
  frame_id: ''
name:
- joint_1_s
- joint_2_l
- joint_3_u
- joint_4_r
- joint_5_b
- joint_6_t
- joint_0_rail
position:
- 0.0
- 6.9410895379440775e-06
- -7.631745213361399e-06
- 0.0
- 0.0
- 0.0
- -610.4629943469697
velocity:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
effort:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
```

As currently configured, the zero position of the rail is at the far right side of the workcell, and as the rail moves to the left the position increases in magnitude. At the far left side of the workcell the reported position is about `-9000.0` mm.
