### DISCUSSION TITLE
Robot has trouble to complete trajectory at medium to high speeds

### DISCUSSION THREAD

**Discussion by JonaRo4** [Yaskawa-Global/motoros2#422] [Troubleshooting] [answered]
Hello everyone,
im using a Yaskawa HC10 robot with YRC1000 controller and Motoros2 and Moveit2. Im using follow joint trajectory mode to implement a PnP application off a moving conveyor belt. 
Using
setMaxVelocityScalingFactor();
setMaxAccelerationScalingFactor();
i can set the speed and acceleration from 0.1 to 1.0. For the scaling factor, Moveit2 is referencing this joint_limits.yaml.
<details>
<summary>joint_limits.yaml</summary>

```
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  joint_1_s:
    has_velocity_limits: true
    max_velocity: 2.2689280275926285
    has_acceleration_limits: true
    max_acceleration: 3.75
  joint_2_l:
    has_velocity_limits: true
    max_velocity: 2.2689280275926285
    has_acceleration_limits: true
    max_acceleration: 1.875
  joint_3_u:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 2.5
  joint_4_r:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 3.125
  joint_5_b:
    has_velocity_limits: true
    max_velocity: 4.3633231299858242
    has_acceleration_limits: true
    max_acceleration: 3.75
  joint_6_t:
    has_velocity_limits: true
    max_velocity: 4.3633231299858242
    has_acceleration_limits: true
    max_acceleration: 5.0
```

</details>

At speed and acceleration of 0.1 (10% of maximum speed) the robot completes the trajectory in a very smooth manner. However, when i try to use full speed or even just 50 %, it keeps interrupting the trajectory without an error message in Moveit2. 

But the YRC1000 pendant shows me the **Alarm 4315** with:

**Alarm content**: A collision was detected because of the interference between the manipulator and a peripheral device. The external force applied to the robot exceeded the threshold.

**Cause**: Setting error

However, there is no visible collision.

Furthermore the movement of the robot is generally very stuttery and jerky at medium to high speeds, which also leads to trajectory interruptions. 
Is this a hardware issue or a software issue? 

Regarding the FSU of the robot, there are no speed limits or joint limits set on the YRC1000 Pendant, just robot range limits.

I would appreciate any ideas as to what could prevent the robot of completing the trajectory at higher speeds.

Thank you very much in advance.
