### ISSUE TITLE
`Warning: Group 0 - Time difference between endTrajData (...) and startTrajData (...) is 0 or less.`

### ISSUE THREAD

**Issue by gavanderhoorn** [Yaskawa-Global/motoros2#255]
Just happened to notice it while working on something:

```
Processing next point in trajectory [Group #0 - T=3.899: ( 1.2294,  0.0132, -1.4978,  1.2743,  0.1970,  2.4911)]
Processing next point in trajectory [Group #1 - T=3.899: ( 0.8486,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000)]
Processing next point in trajectory [Group #0 - T=4.000: ( 1.2287,  0.0112, -1.5007,  1.2794,  0.2003,  2.4942)]
Processing next point in trajectory [Group #1 - T=4.000: ( 0.8482,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000)]
Processing next point in trajectory [Group #0 - T=4.000: ( 1.2287,  0.0112, -1.5007,  1.2794,  0.2003,  2.4942)]
Warning: Group 0 - Time difference between endTrajData (4000) and startTrajData (4000) is 0 or less.
Processing next point in trajectory [Group #1 - T=4.000: ( 0.8482,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000)]
Warning: Group 1 - Time difference between endTrajData (4000) and startTrajData (4000) is 0 or less.
```

this could be a problem with the 'input' trajectory (ie: the submitted goal), but I haven't checked yet.

Trajectory generated by MoveIt.

**Comment by gavanderhoorn** [comment]
@ted-miller: would it not make sense to refuse to execute a trajectory which has this problem?

We iterate over all trajectory points when processing the incoming goal, and this seems like it falls in the "malformed input trajectory" category.

**Comment by ted-miller** [comment]
In this case, I don't see a problem with that trajectory. It just seems the last point is duplicated. 

If there were any positional difference in the last two points, then yeah this would be problem. 

So maybe only reject the trajectory if there's no difference, but there is a difference in position?

**Comment by schornakj** [comment]
I had a chance to investigate this today and I think I know what's happening. ROS JointTrajectory messages store durations with nanosecond precision, but MotoROS2[ converts them to use millisecond precision](https://github.com/Yaskawa-Global/motoros2/blob/9f5ccf6dcf86cb3be340c850cb3aa990aa9c4bd6/src/MotionControl.c#L303-L321). Sometimes the output from motion planning and time parameterization includes trajectory points that are separated by less than a millisecond, and that situation causes this check to fail because when cast to millisecond precision the points have the same timestamp.

Here's a trajectory I logged that shows the issue:
```
0:
 positions:
 - 1.75795
 - -0.104497
 - -0.728471
 - -0.443087
 - 0.441418
 - -1.20692
 velocities:
 - 0.00000
 - -0.00000
 - -0.00000
 - -0.00000
 - -0.00000
 - 0.00000
 accelerations:
 - 0.00000
 - 0.00000
 - 0.00000
 - 0.00000
 - 0.00000
 - 0.00000     
 effort: []
 time_from_start:
   sec: 0
   nanosec: 0
 
 1:
 positions:
 - 1.75795
 - -0.104497
 - -0.728471
 - -0.443087
 - 0.441418
 - -1.20692
 velocities:
 - 1.15917e-09
 - -1.00356e-08
 - -7.42579e-09
 - -5.01417e-09
 - -1.91215e-09
 - 4.79032e-09
 accelerations:
 - 0.115917
 - -1.00356
 - -0.742579
 - -0.501417
 - -0.191215
 - 0.479032
 effort: []
 time_from_start:
   sec: 0
   nanosec: 10
```

> this could be a problem with the 'input' trajectory (ie: the submitted goal), but I haven't checked yet.

In this case the input trajectory was valid (timestamps monotonically increasing) and can be executed by my mock hardware interface, so I think MotoROS2 should be able to ingest it without failing. It probably isn't possible for the robot to actually perform the precise requested motion since the jerk is too high, so maybe the solution is to do some sort of filtering.
